### ISSUE TITLE
NewFromHash() function failed with panic

### ISSUE THREAD

**Issue by AlexeyKondakov** [GehirnInc/crypt#5]
```
package main

import (
    "github.com/GehirnInc/crypt"
    _ "github.com/GehirnInc/crypt/sha256_crypt"
)

func main() {
    crypt.NewFromHash("$5$zt1EpbKWbqit0l8h")
}
```

Output:

panic: crypt: requested crypt function is unavailable

**Comment by yosida95** [comment]
Thank you for reporting the issue.

I fixed this in 6c0105aabd460ae06c87afeb5a47c869f6a7557e. Please updating the library and then recompiling the your code.
